### ISSUE TITLE
Failure to load checkpoint

### ISSUE THREAD

**Issue by JinlongYANG** [non-void/VirtualBones#1]
Hi,

Thanks for sharing the amazing work and the code!

When I tried to run the demo code following the description, a failure of loading checkpoint happened.

> magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, 'v'.

You can simply reproduce this by running torch.load('./VirtualBones/assets/dress02/checkpoints/SSDR.pth.tar')

**Comment by non-void** [comment]
Hello,

This might be incomplete download of models.

The models are uploaded via git-lfs, maybe you can also use git-lfs to download the models using `git-lfs pull`, or directly download the raw model from the url such as https://github.com/non-void/VirtualBones/blob/main/assets/dress02/checkpoints/SSDR.pth.tar .

Here are some similar problems raised by others. I hope these references can help:

https://github.com/svip-lab/PlanarReconstruction/issues/28
https://github.com/DwangoMediaVillage/3dpose_gan/issues/1
https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key
https://discourse.aicrowd.com/t/solved-running-test-submission-py-runs-into-pickle-unpicklingerror-invalid-load-key-v/6458/3

**Comment by JinlongYANG** [comment]
Yes you were right, it was the incomplete download of checkpoints.

Thanks for pointing out the solutions!

**Comment by zztianzz** [comment]
Hi, can you share the checkpoints? It seems that the checkpoints can not download now. Thanks a lot!
