### ISSUE TITLE
Virtual Bones Generation

### ISSUE THREAD

**Issue by kunkun0w0** [non-void/VirtualBones#10]
After reading your paper, I'm still not sure if the virtual bones are generated from a single motion sequence or from all motion sequences of a particular garment.

**Comment by kunkun0w0** [comment]
And when I use the dem-bones parameter in your supplementary, I get a weird result.
`call "../bin/Windows/DemBones.exe" -i="dress.fbx" -a="dress_shape00_01_01.abc" -b=40 -o="dress_40.fbx" -n=100 --nWeightsIters=3 -z=8`
![image](https://user-images.githubusercontent.com/56219029/196323433-4768cf1e-bcbb-4a97-a100-6dd7b5cfbfd0.png)
The decomposition result is so small and looks bad. And the RMSE is about 0.1.
![image](https://user-images.githubusercontent.com/56219029/196324068-cf894117-8320-48e3-bf72-a2f354c7e9d7.png)

Can you give me some suggestions?

**Comment by non-void** [comment]
The virtual bones are generated from all motion sequences of a particular garment.

**Comment by kunkun0w0** [comment]
Sorry, I am not familiar with dem-bones and I am struggling with processing the data.
I have some `.abc` files and the init pose `.fbx`.

Do I need to concatenate all the motion sequences into one `.abc` file?
Or just use some scripts in dem-bones?

**Comment by non-void** [comment]
Yes, you have to concatenate them

In our experiment, we concatenate them in to an ".npy" file and modified the file reader of dem-bones.

**Comment by kunkun0w0** [comment]
Sorry for disturbing you again.
Have you met such a problem when decomposing?
Dem-bones can only run one loop in bones initialization.

![image](https://user-images.githubusercontent.com/56219029/196591307-383537c2-e043-41d4-8bb8-210acd7f9f32.png)

**Comment by non-void** [comment]
Sorry, I have not met such problem, you may check the input data and source code of dem-bones.

**Comment by kunkun0w0** [comment]
Sorry, I am not familiar with FBX SDK.
How can I extract skin weight and bones transformation from the `.fbx` files?
Do you have a recommended tool?

(,,•́ . •̀,,)

**Comment by non-void** [comment]
I use Maya and write python scripts to extract info from fbx files.

**Comment by handhp1** [comment]
@kunkun0w0 Hi, how did you solve the problem when generating virtual bones? I'm having same issue as you. The bone generation results look messy. Thank you.
