### ISSUE TITLE
Some question about trainig code implementation

### ISSUE THREAD

**Issue by kunkun0w0** [non-void/VirtualBones#11]
Hi, is me again!

I meet some problems in implementing VirtualBones according to the paper.

1. The paper only provides the learning rate schedule, but hasn't provided the number of total train epochs.
2. I am not sure about the low-frequency module and high-frequency module are trained separately or jointly.
3. How to implement the Laplacian Loss? I use the `get_mesh_laplacian` in PyG, however, the values in the laplacian matrix are extremely high (up to 1e6). The LBS loss is only about 1e-2, so it seems strange if I set the weight of laplacian loss equal to 1 according to the paper.

**Comment by non-void** [comment]
1. We set the max epoch to 1000, and batch size to 8 for low-freq training, and similar setting for high-freq training. We found that the training does not need to reach maximun epoch to converge, so you can stop training as the loss become stable.
2. We first train the low-freq module and use the output of low-freq module to train the high-freq module.
3. The laplacian loss is implemented by hand written code, we calculate the laplacian matrix and multiply the matrix and output vertex position.

**Comment by kunkun0w0** [comment]
Sorry, I am not sure why we need to ***multiply*** the matrix and output vertex position.

Isn't the Laplacian matrix used in the paper the Cotangent Laplacian for triangle mesh?

**Comment by kunkun0w0** [comment]
> 

Are you using the Laplacian matrix of the graph, then multiplying it with the vertex position?

**Comment by non-void** [comment]
We use a simpler version of Laplacian matrix, suppose vertex i connect to vertex j, then L[i, j]  = L[j, i] = -1 and L[i, i] ++, L[j, j]++

**Comment by kunkun0w0** [comment]
> Sorry, I am not sure why we need to _**multiply**_ the matrix and output vertex position.
> 
> Isn't the Laplacian matrix used in the paper the Cotangent Laplacian for triangle mesh?

Are you using the Laplacian matrix of the graph, then multiplying it with the vertex position?

**Comment by kunkun0w0** [comment]
> We use a simpler version of Laplacian matrix, suppose vertex i connect to vertex j, then L[i, j] = L[j, i] = -1 and L[i, i] ++, L[j, j]++

oh, I see.

**Comment by kunkun0w0** [comment]
A small question about the data process:
Do I need to remove the global transformation for each frame, then do the SSDR?

**Comment by non-void** [comment]
of course, you can do the inverse of line 123-130 of run_motionnet.py, where we add global transformation to the prediction results

**Comment by kunkun0w0** [comment]
Thanks! I get it.

But why the translations are corresponding with each frame, but all rotations are from the first frame?

![image](https://user-images.githubusercontent.com/56219029/198566683-6b1dd890-6363-494c-9310-80dbc506f763.png)

**Comment by kunkun0w0** [comment]
> 

I mean, why not use `pose[frame]` ?

**Comment by non-void** [comment]
pose[0] is the rotation of the root joint, not the first frame

**Comment by kunkun0w0** [comment]
Sorry, orz
My fault.......
Hope I can reproduce this awesome project soon.

**Comment by kunkun0w0** [comment]
When implementing the collision loss, I fail to find the nearest neighbor in body vertices for garment vertices due to the O(n2) distance map, i.e. CUDA out of memory.

So I wonder is there any efficient way to achieve this function in a RTX2080Ti?

And I am also curious about how to get the body vertices normal. Do you just average the face normals or estimate the normals from the points cloud?

**Comment by non-void** [comment]
We also use the O(n2) distance map. You can try to simplify the body mesh, if out of memory.

The vertice normal can be calculated using face normals.

**Comment by kunkun0w0** [comment]
Thanks for the previous patient reply!

I successfully complete the training code of VirtualBones, and I come into the last term, i.e. implement the STED.

I have read the reference paper, and I wonder about the setting of STED's parameters used in VirtualBones.
(Topological neighborhood width, Speed window width, and the relating constant c)

Or do you just use some package?

**Comment by non-void** [comment]
We implemented it, and set the topological neighbor width to 1, window width to 5, and c to 0.2 (instead of 9e-5 in the original paper)

**Comment by kunkun0w0** [comment]
Oh, the STED shown in your paper is not multiplied by 1000, right?

**Comment by non-void** [comment]
yes, we keep the original value

**Comment by kunkun0w0** [comment]
And RMSE and Hausdorff in your paper are all multiplied by 1000? orz

**Comment by non-void** [comment]
Yes, we multiply it

**Comment by kunkun0w0** [comment]
Sorry to bother you again

![image](https://user-images.githubusercontent.com/56219029/200385191-28fd8465-4068-4273-8461-83d2d109ea7d.png)
I found that my HF prediction was so rough.
I am not sure whether you add laplacian loss when training the HF model or not.

**Comment by non-void** [comment]
It's wierd, and we have not met this in our implementation. 

You can try to add laplacian loss for the HF training, using the same loss weight as the LF part.

**Comment by kunkun0w0** [comment]
1. Would the smooth strategy effect the HF training?
I use the uniform smoothing type. There is another choice, i.e., cotangent, in https://github.com/chaitanya100100/TailorNet/blob/62de3c947e7ceaed446b7e40915ec033c7cd55cf/utils/diffusion_smoothing.py .

2. Maybe the normalization?
Due to the translation directions are not the same (some run along x, some run along z), so I normalize the pose and translation  within each clips, not in whole dataset.

**Comment by non-void** [comment]
In our implementation, we use uniform smoothing.

Since the translation and rotation of each frame is known, we remove garments' global transformation on each frame.

**Comment by kunkun0w0** [comment]
I mean the mormalization of `motion_signature` which is the LF model input.
I notices that you do the normalization which contains the normalization of global translation and rotation.
https://github.com/non-void/VirtualBones/blob/afb378e1216081395010943239461bb38701d77c/run_motionnet.py#L85-L86
And you use the global translation for LF model inference.
https://github.com/non-void/VirtualBones/blob/afb378e1216081395010943239461bb38701d77c/run_motionnet.py#L97



> Since the translation and rotation of each frame is known, we remove garments' global transformation on each frame.

Do you mean that the LF model input actually does not contain global rotation and translation during vto-dataset training?

If we need them, should I normalize within clips or within whole dataset?

**Comment by non-void** [comment]
The inputs of training and inference are the same, and contains the global translation and rotation of body. We just remove the MESH's global transformation.
