### ISSUE TITLE
VirtualBones in TailorNet dataset

### ISSUE THREAD

**Issue by kunkun0w0** [non-void/VirtualBones#13]
I noticed that the TailorNet dataset is a static garment simulation dataset.
So how do you calculate the STED, i.e., how to set `dt`?

Moreover, each clip in the TailorNet dataset contains both discontinuous and continuous movements, did you choose only the continuous part or did you use all of them for training?

**Comment by non-void** [comment]
We use the continuous part for training, and split 2 clips for testing and the rest for training
