### ISSUE TITLE
Can't download checkpoint

### ISSUE THREAD

**Issue by zztianzz** [non-void/VirtualBones#16]
Hi, Thanks for your awosome work! But  when i want to download the checkpoint, I meet a problem: "batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access." It seems that the checkpoint file can't download. Can you upload the checkpoints again? Thanks a lot!

**Comment by non-void** [comment]
hello, i have upgraded my github plan, please try again

**Comment by zztianzz** [comment]
Thanks!
