### ISSUE TITLE
Missing files: assets/dress0*/garment.obj and assets/dress0*/SSDR/u.obj

### ISSUE THREAD

**Issue by JinlongYANG** [non-void/VirtualBones#2]
Hi,

when I tried to run the demo, I found there were .obj files missing:

> assets/dress0*/garment.obj 
> and assets/dress0*/SSDR/u.obj

I assume the garment.obj files correspond to
https://github.com/sig22virtualbones/VirtualBonesDataset/blob/main/dress0*/template.obj
But could you please let me know where I can get the u.obj files?

Thanks!

**Comment by non-void** [comment]
Sorry for the inconvenience

I have uploaded these files

**Comment by JinlongYANG** [comment]
Thank you!
