### ISSUE TITLE
how to render obj file?

### ISSUE THREAD

**Issue by skeras** [non-void/VirtualBones#3]
Hi,
   Thanks for your great project.
   How to render result obj file as tease.jpg?

**Comment by non-void** [comment]
Hello,

We use Maya and arnold renderer to render all the images in the paper. The positions and directions of models, lights, cameras are manually adjusted.

**Comment by skeras** [comment]
Thank you for your quick reply.
I am comfused how to use garment dress human body module? such as smpl  smplx etc...

**Comment by non-void** [comment]
For the dresses in the teaser, we use the private body model provided by NExT studio.

Sorry, we are not allowed to provide this body model.
