### ISSUE TITLE
How to train your model and question about the number of input motion frames.

### ISSUE THREAD

**Issue by lanchen2019** [non-void/VirtualBones#4]
Congratulations! Thanks a lot for releasing your pre-trained model and test code! Would you like to release the training code? Besides, I saw the number of input motions was 1 when testing. What is the number of input motions at the training stage?  Since one frame is not able to capture dynamic details and may cause ambiguity.

**Comment by non-void** [comment]
Hello, 

I was not allowed to release the training code, but I believe the paper has provided enough information for the implementation. If you have any question about training, please do not hesitate to ask me.

We use a recurrent neural network (GRU in our implementation) for the dynamics. Every frame, the network takes the motion of the current frame and the information from previous frames (hidden) as inputs, besides generating the results, it also update the information (new hidden). Please check line 102-103 and line 114-115 of the run_motionnet.py.

**Comment by lanchen2019** [comment]
Got it. Thanks so much!

**Comment by xiangdonglai** [comment]
I have a question for the authors: when preparing the data for training, did you use any public implementation of SSDR, or your own implementation.

Thanks in advance.

**Comment by non-void** [comment]
We use https://github.com/electronicarts/dem-bones .

**Comment by kunkun0w0** [comment]
It seems that the `u.obj` and the `rest.obj` are the same in `./assets/***/SSDR/`.
And I'm not really sure what these two files mean.

Is `u.obj` low-fequency mesh and `rest.obj` high-fequency mesh?
