### ISSUE TITLE
How to install torch_geometric correctly?

### ISSUE THREAD

**Issue by Zhangjzh** [non-void/VirtualBones#5]
I installed torch geometric. However, it does not work correctly. I got following error.
![image](https://user-images.githubusercontent.com/49779683/174427377-0ce06ffb-d628-4774-873f-d9147e20d12e.png)

**Comment by non-void** [comment]
Sorry, I have no idea about this error. The issue may be related to the installation of pytorch geometric.

**Comment by qiji77** [comment]
maybe you can try torch_sparse==0.6.12?
