### ISSUE TITLE
Is the network fitted to the specific garment or can it be arbitrary?

### ISSUE THREAD

**Issue by fire** [non-void/VirtualBones#6]
https://github.com/non-void/VirtualBones/blob/main/assets/dress02/SSDR/rest.obj

Can I change the garment without retraining?

Your paper mentions sampling 10 sets of simulation parameters with data via dance motions of MikuMikuDance (MMD) from Houdini Vellum simulation system [SideFX 2021].

Do I have to make a 3d model, put the new garment on the avatar and then run the Vellum simulation?

The training procedure is unclear.

**Comment by non-void** [comment]
The network is trained for a single garment. We have to retrain the network for a new garment.
