### ISSUE TITLE
Format/order of the input joint rotation

### ISSUE THREAD

**Issue by jinyx728** [non-void/VirtualBones#8]
Hi. This is a very interesting work!

I am wondering if you can share more about the format of the input. I am trying to test your network with new animations other than the 5 animations included in this repo. To achieve this I need to know the order of the input joint rotations (e.g. root, pelvis, spine ...). Can you provide more information about how the input vector is constructed? All I know from the data is that the human body has 52 joints, and 20 of them are used as input of the network, but I don't know exactly what they are and how they are ordered.

Thanks!

**Comment by non-void** [comment]
Hello, the correspondence between joints and index of the array is as follows, which is similar with AMASS dataset:

           "1": "thigh_l",
            "2": "thigh_r",
            "4": "calf_l",
            "5": "calf_r",
            "7": "foot_l",
            "8": "foot_r",
            "10": "ball_l",
            "11": "ball_r",
            "13": "clavicle_l",
            "14": "clavicle_r",
            "16": "upperarm_l",
            "17": "upperarm_r",
            "18": "lowerarm_l",
            "19": "lowerarm_r",
            "0": "pelvis",
            "3": "spine_01",
            "6": "spine_03",
            "9": "spine_05",
            "12": "neck_01",
            "15": "head"

**Comment by myeongjinleee** [comment]
> Hello, the correspondence between joints and index of the array is as follows, which is similar with AMASS dataset:
> 
> ```
>        "1": "thigh_l",
>         "2": "thigh_r",
>         "4": "calf_l",
>         "5": "calf_r",
>         "7": "foot_l",
>         "8": "foot_r",
>         "10": "ball_l",
>         "11": "ball_r",
>         "13": "clavicle_l",
>         "14": "clavicle_r",
>         "16": "upperarm_l",
>         "17": "upperarm_r",
>         "18": "lowerarm_l",
>         "19": "lowerarm_r",
>         "0": "pelvis",
>         "3": "spine_01",
>         "6": "spine_03",
>         "9": "spine_05",
>         "12": "neck_01",
>         "15": "head"
> ```

what's "ball" joint referring to?
