### ISSUE TITLE
What is the difference between u.obj and rest.obj?

### ISSUE THREAD

**Issue by kunkun0w0** [non-void/VirtualBones#9]
Hi. This is a very cool work!
But I am confused the mean of some `.obj`.

It seems that the `u.obj` and the `rest.obj` are the same in `./assets/***/SSDR/`.
And I'm not really sure what these two files mean.

Is `u.obj` low-fequency mesh and `rest.obj` high-fequency mesh?

**Comment by non-void** [comment]
They are the same rest pose mesh for the SSDR, which generate the low-frequency meshes.

**Comment by kunkun0w0** [comment]
Thanks for your quick reply! 

And I have one more question that did you use any public implementation of Laplacian smoothing, or your own implementation when attaining low-fequency.

**Comment by non-void** [comment]
We use the implementation in  https://github.com/chaitanya100100/TailorNet/blob/62de3c947e7ceaed446b7e40915ec033c7cd55cf/utils/diffusion_smoothing.py

**Comment by kunkun0w0** [comment]
Thanks!
(｡･ω･｡)ﾉ♡
